owner: foramil-dev
repo: formail-status

sites:
  - name: formail.dev
    url: https://formail.dev
  - name: docs
    url: https://docs.formail.dev
  - name: releases
    url: https://releases.formail.dev

status-website:
  cname: status.formail.dev
  baseUrl: /formail-status
  logoUrl: https://www.formail.dev/_next/image?url=/logo.png&w=2048&q=75
  name: Formail
  navbar:
    - title: Status
      href: /
    - title: Formail
      href: https://formail.dev
